"""
Stage 7's README conclusion: the combining rule can't fix a URL model that's confidently wrong,
only one that's mildly wrong. GitHub and Stack Overflow links still score 99%+ phishing because
the training data has never actually seen real URLs shaped like theirs, PhiUSIIL's legitimate
URLs are bare homepages, and even the generated paths in `_generate_realistic_path`
(src/url_data_loading.py) only go 1-4 segments deep and pick each segment's shape independently,
so they rarely land on GitHub's "five word segments deep" or Stack Overflow's specific
"word/numeric-id/long-hyphenated-slug" combination.

This is a set of genuinely real, hand-assembled legitimate URLs (same approach as the 100 in
src/real_url_eval.py, not a live crawl, see that file's docstring for why that's fine here) to
mix into the actual training data instead of just using them to test with. Weighted heavily
towards the categories stage 6 and 7 found were still broken, GitHub and Stack Overflow
especially, with smaller amounts everywhere else for balance.

Important: every URL in here is different from the ones in src/real_url_eval.py's
REAL_LEGITIMATE_URLS. Training on the exact URLs used to measure the model would make the
false-positive numbers look better than they actually are, tested by
tests/test_real_legit_urls.py.
"""

REAL_LEGIT_TRAINING_URLS = {
    "github": [
        "https://github.com/torvalds/linux/tree/master/kernel",
        "https://github.com/python/cpython/blob/main/Lib/asyncio/tasks.py",
        "https://github.com/facebook/react/pull/27513",
        "https://github.com/microsoft/TypeScript/issues/58925",
        "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/base_layer.py",
        "https://github.com/rust-lang/rust/commit/9f6a2a2e1c3b4d5e6f7a8b9c0d1e2f3a4b5c6d7e",
        "https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go",
        "https://github.com/django/django/blob/main/django/db/models/fields/__init__.py",
        "https://github.com/nodejs/node/pull/50123",
        "https://github.com/golang/go/issues/64521",
        "https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst",
        "https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/SparkContext.scala",
        "https://github.com/redis/redis/blob/unstable/src/server.c",
        "https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/IndexService.java",
        "https://github.com/vercel/next.js/blob/canary/packages/next/src/server/next-server.ts",
        "https://github.com/facebook/react-native/issues/44210",
        "https://github.com/angular/angular/blob/main/packages/core/src/render3/instructions/shared.ts",
        "https://github.com/vuejs/core/blob/main/packages/reactivity/src/reactive.ts",
        "https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php",
        "https://github.com/rails/rails/blob/main/activerecord/lib/active_record/base.rb",
        "https://github.com/pandas-dev/pandas/pull/58120",
        "https://github.com/numpy/numpy/blob/main/numpy/core/src/multiarray/arraytypes.c.src",
        "https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/ensemble/_forest.py",
        "https://github.com/pytorch/pytorch/issues/128394",
        "https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/modeling_bert.py",
        "https://github.com/openai/gym/blob/master/gym/core.py",
        "https://github.com/khaidaodev/sign-language-recognition/blob/main/src/cnn_baseline.py",
        "https://github.com/khaidaodev/sign-language-recognition/blob/main/demo/webcam_demo.py",
        "https://github.com/microsoft/vscode/pull/213456",
        "https://github.com/nodejs/node/blob/main/lib/internal/modules/cjs/loader.js",
    ],
    "stackoverflow": [
        "https://stackoverflow.com/questions/1520138/how-do-i-check-if-a-string-contains-a-substring-in-javascript",
        "https://stackoverflow.com/questions/171251/how-can-i-find-the-methods-of-an-object",
        "https://stackoverflow.com/questions/2870499/why-doesnt-c-have-reflection",
        "https://stackoverflow.com/questions/3437059/does-python-have-a-string-contains-substring-method",
        "https://stackoverflow.com/questions/493386/comparing-tuples-in-python",
        "https://stackoverflow.com/questions/2352181/how-can-i-time-a-code-segment-for-testing-performance-with-pythons-timeit",
        "https://stackoverflow.com/questions/141291/how-to-simulate-target-blank-in-javascript",
        "https://stackoverflow.com/questions/50120/how-can-i-add-new-array-elements-at-the-beginning-of-an-array-in-javascript",
        "https://stackoverflow.com/questions/613183/how-to-produce-a-common-graphviz-graph-layout",
        "https://stackoverflow.com/questions/4934806/how-can-i-find-a-scripts-directory-with-python",
        "https://stackoverflow.com/questions/610883/how-to-know-if-an-object-has-an-attribute-in-python",
        "https://stackoverflow.com/questions/3223043/why-does-changing-0-1f-to-0-slow-down-performance-by-10x",
        "https://stackoverflow.com/questions/2130016/splitting-a-string-into-a-set-number-of-substrings-in-python",
        "https://stackoverflow.com/questions/517923/what-is-the-purpose-of-the-init-py-file",
        "https://stackoverflow.com/questions/16096754/how-to-print-instances-of-a-class-using-print",
        "https://stackoverflow.com/questions/29528092/why-do-people-write-usr-bin-python-on-the-first-line-of-a-python-script",
        "https://stackoverflow.com/questions/61151/where-do-i-put-a-simple-generic-html-decoder",
        "https://stackoverflow.com/questions/6996603/how-to-delete-a-file-or-folder",
        "https://stackoverflow.com/questions/9938446/how-do-i-split-a-string-having-both-comma-and-space-as-delimiters",
        "https://stackoverflow.com/questions/430757/how-to-remove-null-elements-from-an-array",
        "https://stackoverflow.com/questions/1029023/pythons-inbuilt-sort-function-efficiency",
        "https://stackoverflow.com/questions/2632205/why-does-python-have-a-limit-on-the-number-of-static-nested-blocks",
        "https://stackoverflow.com/questions/394809/does-python-have-a-ternary-conditional-operator",
        "https://stackoverflow.com/questions/373194/php-static-vs-self",
        "https://stackoverflow.com/questions/149055/how-can-i-format-numbers-as-currency-strings",
        "https://stackoverflow.com/questions/1091524/what-is-a-lambda-expression-in-c",
        "https://stackoverflow.com/questions/336859/how-do-i-clone-a-generic-list-in-c",
        "https://stackoverflow.com/questions/2255878/how-to-parse-lines-from-a-file-in-python",
        "https://stackoverflow.com/questions/1720421/merge-two-arrays-in-javascript-and-remove-duplicate-items",
        "https://stackoverflow.com/questions/728891/how-to-list-all-functions-in-a-python-module",
    ],
    "gov_uk": [
        "https://www.gov.uk/check-state-pension",
        "https://www.gov.uk/renew-driving-licence",
        "https://www.gov.uk/report-benefit-fraud",
        "https://www.gov.uk/jobseekers-allowance",
        "https://www.gov.uk/book-a-driving-test",
        "https://www.gov.uk/check-mot-history",
        "https://www.gov.uk/pay-council-tax",
        "https://www.gov.uk/claim-tax-refund",
        "https://www.gov.uk/register-birth",
        "https://www.gov.uk/marriage-visa",
        "https://www.gov.uk/apply-first-provisional-driving-licence",
        "https://www.gov.uk/child-benefit",
        "https://www.gov.uk/housing-benefit",
        "https://www.gov.uk/personal-independence-payment",
        "https://www.gov.uk/state-pension-age",
        "https://www.gov.uk/apply-for-council-housing",
        "https://www.gov.uk/vehicle-tax",
        "https://www.gov.uk/check-vehicle-tax",
        "https://www.gov.uk/browse/benefits",
        "https://www.gov.uk/browse/tax",
        "https://www.gov.uk/browse/visas-immigration",
        "https://www.gov.uk/browse/education",
        "https://www.gov.uk/apply-online-to-renew-your-passport",
        "https://www.gov.uk/renew-adult-passport",
        "https://www.gov.uk/universal-credit/how-to-claim",
    ],
    "blog": [
        "https://medium.com/@techwriter2026/the-hidden-cost-of-technical-debt-in-fast-growing-startups-4f8a9b2c1d3e",
        "https://dev.to/sarahcodes/five-lessons-i-learned-shipping-my-first-saas-product-3k2p",
        "https://medium.com/@ai-researcher/why-large-language-models-still-struggle-with-basic-arithmetic-9a1b2c3d4e5f",
        "https://dev.to/johndoe/understanding-closures-in-javascript-a-beginners-guide-2ab4",
        "https://medium.com/@productmanager2026/how-i-prioritise-my-roadmap-using-a-simple-scoring-model-7d8e9f0a1b2c",
        "https://overreacted.io/a-complete-guide-to-useeffect/",
        "https://css-tricks.com/snippets/css/a-guide-to-flexbox/",
        "https://kentcdodds.com/blog/how-to-use-react-context-effectively",
        "https://tania.dev/why-i-still-use-vim-in-2026/",
        "https://jvns.ca/blog/2023/07/29/understanding-dns-in-30-minutes/",
        "https://blog.logrocket.com/understanding-react-server-components/",
        "https://www.smashingmagazine.com/2026/02/complete-guide-css-grid/",
        "https://blog.pragmaticengineer.com/how-big-tech-runs-tech-projects/",
        "https://simonwillison.net/2026/Jan/12/ai-agents/",
        "https://blog.cleancoder.com/uncle-bob/2026/01/10/what-is-clean-architecture.html",
        "https://increment.com/testing/testing-at-scale/",
        "https://eng.uber.com/microservice-architecture/",
        "https://netflixtechblog.com/optimizing-video-encoding-at-scale-abc123def456",
        "https://stackoverflow.blog/2026/02/03/why-developers-still-love-the-command-line/",
        "https://dev.to/khaidaodev/building-a-phishing-detector-from-scratch-lessons-learned-4kp9",
    ],
    "docs": [
        "https://docs.python.org/3/library/asyncio-task.html",
        "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch",
        "https://reactjs.org/docs/hooks-effect.html",
        "https://docs.djangoproject.com/en/5.0/topics/auth/default/",
        "https://www.typescriptlang.org/docs/handbook/2/generics.html",
        "https://vitejs.dev/guide/features.html",
        "https://tailwindcss.com/docs/responsive-design",
        "https://docs.docker.com/engine/reference/commandline/build/",
        "https://kubernetes.io/docs/concepts/workloads/pods/",
        "https://redis.io/docs/latest/commands/expire/",
        "https://www.postgresql.org/docs/current/indexes-types.html",
        "https://numpy.org/doc/stable/reference/generated/numpy.array.html",
        "https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html",
        "https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html",
        "https://nodejs.org/api/stream.html",
    ],
    "wikipedia": [
        "https://en.wikipedia.org/wiki/Deep_learning",
        "https://en.wikipedia.org/wiki/Neural_network",
        "https://en.wikipedia.org/wiki/Support_vector_machine",
        "https://en.wikipedia.org/wiki/Natural_language_processing",
        "https://en.wikipedia.org/wiki/Computer_security",
        "https://en.wikipedia.org/wiki/Cryptography",
        "https://en.wikipedia.org/wiki/United_Kingdom",
        "https://en.wikipedia.org/wiki/University_of_Greenwich",
        "https://en.wikipedia.org/wiki/GitHub",
        "https://en.wikipedia.org/wiki/Stack_Overflow",
    ],
    "news": [
        "https://www.bbc.co.uk/news/business-68123456",
        "https://www.bbc.co.uk/news/science-environment-68234567",
        "https://www.theguardian.com/technology/2026/feb/03/cybersecurity-uk-firms",
        "https://www.reuters.com/business/technology/",
        "https://www.independent.co.uk/tech/ai-news-b1234567.html",
        "https://www.telegraph.co.uk/technology/2026/03/05/phishing-scams-rise/",
        "https://news.sky.com/story/cyber-attack-warning-87654321",
        "https://www.ft.com/content/12345678-abcd-4321-abcd-1234567890ab",
        "https://www.nytimes.com/2026/02/20/technology/cybersecurity-report.html",
        "https://www.standard.co.uk/news/uk/london-tech-news-b7654321.html",
    ],
    "ecommerce": [
        "https://www.amazon.co.uk/dp/B0CX1234YZ",
        "https://www.amazon.com/dp/B0D5678ABC",
        "https://www.ebay.co.uk/itm/187654321098",
        "https://www.asos.com/topshop/topshop-mini-skirt/prd/98765432",
        "https://www.argos.co.uk/product/9876543",
        "https://www.johnlewis.com/john-lewis-partners-dining-table/p7654321",
        "https://www.next.co.uk/style/st987654/321098",
        "https://www.currys.co.uk/products/tv-9876543.html",
        "https://www.marksandspencer.com/mens-clothing/p/clp70987654",
        "https://www.etsy.com/listing/9876543210/custom-name-necklace",
    ],
    "university": [
        "https://www.gre.ac.uk/undergraduate/courses/computer-science-bsc-hons",
        "https://www.gre.ac.uk/about-us/our-history",
        "https://www.york.ac.uk/study/undergraduate/courses/2026/computer-science/",
        "https://www.southampton.ac.uk/courses/computer-science-bsc",
        "https://www.warwik.ac.uk/study/undergraduate/courses/computerscience/",
        "https://www.sheffield.ac.uk/undergraduate/courses/2026/computer-science-bsc",
        "https://www.qmul.ac.uk/undergraduate/courses/computer-science/",
        "https://www.city.ac.uk/courses/undergraduate/computer-science",
        "https://www.lse.ac.uk/study-at-lse/undergraduate/degree-programmes-2026",
        "https://www.bath.ac.uk/courses/undergraduate-2026/bsc-computer-science/",
    ],
    "file_sharing": [
        "https://drive.google.com/file/d/9z8y7x6w5v4u3t2s1r0q/view",
        "https://docs.google.com/document/d/9z8y7x6w5v4u3t2s1r0q/edit",
        "https://docs.google.com/spreadsheets/d/8y7x6w5v4u3t2s1r0qp9/edit",
        "https://www.dropbox.com/s/xy12ab34cd56ef/notes.pdf",
        "https://onedrive.live.com/view.aspx?resid=9876ZYXW5432VUTS!456",
        "https://app.box.com/s/zyx987wvu654tsr321",
        "https://wetransfer.com/downloads/zyx987wvu654tsr321",
        "https://raw.githubusercontent.com/khaidaodev/sign-language-recognition/main/README.md",
        "https://www.icloud.com/iclouddrive/9zyx876wvu543tsr210",
        "https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j",
    ],
}

ALL_REAL_LEGIT_TRAINING_URLS = [url for urls in REAL_LEGIT_TRAINING_URLS.values() for url in urls]


if __name__ == "__main__":
    for category, urls in REAL_LEGIT_TRAINING_URLS.items():
        print(f"{category:15s} {len(urls)}")
    print(f"\ntotal: {len(ALL_REAL_LEGIT_TRAINING_URLS)}")
